#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

// Set path constants
define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH . '/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH . '/autoload.php';

// Load .env file
if (file_exists(CRAFT_BASE_PATH . '/.env')) {
    $dotenv = Dotenv\Dotenv::createImmutable(CRAFT_BASE_PATH);
    $dotenv->load();
}

// Run the app
$app = require CRAFT_VENDOR_PATH . '/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
