allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  72f105f5-bfa7-49fc-8fda-0ba13d88b92f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-30T00:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 39f27e13-9392-42b7-ac8c-44ea60c81296
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a0761fc1-d06e-401d-9fdb-6414967991f5 # text eachSite
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0b421d1-0a2d-4b8a-ba81-cc700c62f0f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7cad947f-8d4f-42ed-b422-b09b0ee0978d # text eachLang
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28542462-3d08-4477-97c9-0fc1c7badae5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f46d09fa-f3a8-4bdf-a162-0c3f0f70f520 # text none
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e837327-98c6-456b-bed6-8df857c76e78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d5da91b-f97b-4f15-b664-bc1e30ee549a # richtext full
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90efab1a-66d1-4a7c-a392-948682c3e77f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f10f92d8-fab4-4f33-989b-241cc89c2e75 # richtext raw
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fc2476d-f5c1-46c3-9ee5-d4b3676b9ac1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 23998c97-074c-4d61-852a-0c583e35ab1a # richtext full none
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f5e7e0b-0c80-4532-b63a-b5f50d4a3902
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b9e93a91-f408-4b66-8b43-f3769cc7804c # richtext raw none
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01e1ceef-744a-403c-a123-8c9684ed93fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1dd44912-9b20-407c-a395-003f9ead4668 # link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eef4b96-4a2f-4d9e-b4c2-c67a89d49f38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 81c56b28-42ff-4f46-820f-659820456750 # link none
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b8c5161-2e67-4291-96a6-d5e685dcd51e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1cd29b52-e7e4-4765-9f5b-cd9d185d7111
        userCondition: null
    thumbFieldKey: null
handle: entry_1
hasTitleField: true
icon: null
name: 'entry 1'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
