color: null
fieldLayouts:
  a7dd07ce-d152-405d-bf50-5780a11942e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-03T07:30:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0d55353-2ed1-483a-b168-93b3e176d4f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-03T07:31:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e96f059b-fe9e-4acd-90c4-bef92d500846 # Matrix With Neo
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ca6c01c-ecf2-4f9c-9dd3-ac6cc52d6a1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce134995-739d-4a25-890a-4f5bddfaa221
        userCondition: null
handle: matrixwithneocontainer
hasTitleField: true
icon: null
name: MatrixWithNeoContainer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
