allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  bc501493-9472-4487-966f-78d507fc07c6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-20T08:12:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1d5c5775-ac64-4443-bbac-bad8a36fc2db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:14:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6c2105d9-a0b4-4c42-83e9-3f1023fd44ce # testNewBlock
            handle: mynewblock1
            instructions: null
            label: myNewBlock1
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9f5adc1-e822-4938-a327-b8d914a86fac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:23:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cbb9d1ca-b408-4fd6-843e-3882ac4532fb # testBlockSubtitle
            handle: null
            instructions: null
            label: 'Sub title 1'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfd763df-4c94-46d8-b72a-c9f8e0fcb7c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:23:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cbb9d1ca-b408-4fd6-843e-3882ac4532fb # testBlockSubtitle
            handle: testblocksubtitle2
            instructions: null
            label: 'Sub title 2'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a1ff8e3-6439-4d0b-bb62-93fe30f88816
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:23:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cbb9d1ca-b408-4fd6-843e-3882ac4532fb # testBlockSubtitle
            handle: testblocksubtitle3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e0b7d2d-2de1-4533-94ea-9aa1d70153c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:23:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cbb9d1ca-b408-4fd6-843e-3882ac4532fb # testBlockSubtitle
            handle: testblocksubtitle4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8e67804-3afc-4184-9eeb-16f389e09f4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:39:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 19664c4f-9a61-42ac-bf1e-c425e4ac4713 # myLink
            handle: link_1
            instructions: null
            label: 'link 1'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aea7cbbb-a675-442d-af85-70f51acf8800
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T08:39:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 19664c4f-9a61-42ac-bf1e-c425e4ac4713 # myLink
            handle: mylink2
            instructions: null
            label: link-2
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 142c0e16-0c2a-447d-b22f-5c84b03a86bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5d72ff5-680b-45fb-a96a-4cc586800b36
        userCondition: null
    thumbFieldKey: null
handle: testBlockContainer
hasTitleField: true
icon: null
name: 'Test block container'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
