allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f1121585-ed28-4489-87cc-d816ea21aa96:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-24T13:10:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4f20e02-a38d-4bf0-b9b8-21be741e98cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T13:12:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 313bc641-6f72-425c-85bd-1d0d22aa0bd0 # test complex Block A
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9420a75-551c-4cec-930f-c2efb0d8a9d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T13:12:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e281e60f-7643-4291-8a93-18558a8aa2ab # test complex Matrix A
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8f2172d-16fc-4002-b243-e2005d8e67fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T13:12:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: be02fa98-e0c0-453d-b484-f02c2eaabeac # test plain text field
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73c90a0a-109c-4af6-8a94-53a4419714b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T13:12:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dff94667-97f1-4ff2-951b-103f60010936 # test complex Block B
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 104cd980-18d3-44dc-89c2-8ec8de047880
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T13:12:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b9e4b409-e3a2-4b5a-8462-1c572af640b3 # test complex Matrix B
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be4ba351-2d08-4db6-9aa8-e2688677242a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5ad008bf-2270-43d0-b5c0-a8e9e94dc584
        userCondition: null
    thumbFieldKey: null
handle: testComplexBlockContainer
hasTitleField: true
icon: null
name: 'test Complex Block Container'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
