color: null
fieldLayouts:
  69154241-dfb5-4883-89c9-9e231bc43e0a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-16T19:10:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0a46c34-5f6b-41a1-b1a3-0c66e114c154
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-16T19:12:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fea1e54-4552-4997-acc8-0467dc3c3569
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d8e66149-ccc0-4138-b6ce-92098e1e8004
        userCondition: null
handle: testSimpleTypeSingle1
hasTitleField: true
icon: null
name: 'Test Simple type single1'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
