allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  61b2f242-45d0-4725-bc6e-c8b68b944b0a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-24T12:50:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6b289b6-96ce-40f6-8caa-692498919fe4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T12:51:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09b173ed-f580-4ac9-a440-a7fb0e949a59 # test content block Link_Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff2b6d25-9147-4768-b1ec-a6339918ad2c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d20dcf2-eaff-4f10-8443-fbd1ce8fd566
        userCondition: null
    thumbFieldKey: null
handle: testBlockContainer
hasTitleField: true
icon: null
name: 'test block Container'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
