color: null
fieldLayouts:
  ac5faed6-ad04-4f8a-9a0f-99449cfff42a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-06T13:09:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ea8b6ae-cb8b-47df-9664-eef984c28788
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad8df684-2715-4da3-9fd3-f6667661923f
        userCondition: null
handle: testTypeSimple2
hasTitleField: false
icon: null
name: 'Test type simple 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
