color: null
fieldLayouts:
  4b6591ea-4c7e-491d-8cc4-666b4f27ad78:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-06T13:07:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f8bd084-5eb0-40f0-81e5-62ff4f8df5fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T13:07:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42480b59-6b29-4f2d-896c-491ce03af675 # Matrix content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60316b9d-3f20-4278-8650-68d3f36d3063
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cd3af04f-37c1-4fd6-9edc-c863deaf151f
        userCondition: null
handle: testTypeComplex2
hasTitleField: false
icon: null
name: 'Test type complex 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
