color: null
fieldLayouts:
  a923cfbb-948c-4f09-9e76-5226e875d783:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-06T13:03:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4aa0d5e7-08c5-4efc-897b-2c54ef62848c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T13:08:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2268a9f-41b0-443d-a818-8e0f9427c242
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T13:08:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42480b59-6b29-4f2d-896c-491ce03af675 # Matrix content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79baadc9-eae0-4101-8a4e-3015979d923a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53eb3323-e1af-4c07-83cf-ead8f18baba0
        userCondition: null
handle: testMatrixNestedType
hasTitleField: true
icon: null
name: ' Test Matrix nested type'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
