baseUrl: 'http://craft-stage.sc.local/'
enabled: true
handle: default
hasUrls: true
language: en
name: 'test Site EN'
primary: true
siteGroup: 45dee176-325e-426d-b3d5-cf9ece27951c # SC-Stage
sortOrder: 1
