childBlocks: '*'
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 947df1bf-e646-4be0-bbb3-a93b6f7c334d # My neo field 1
group: null
groupChildBlockTypes: true
handle: richTextWithImage
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Rich text with image'
topLevel: true
