childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: d7193139-1ed3-4502-beb9-74584bf39fcf # Test type complex
field: f54c31d7-a088-44f5-844e-abeb61bc67e4 # My field neo
fieldLayouts:
  7a913aca-3478-432d-ab24-a7ec3ac8d0d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-06T13:07:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 018ba728-0709-4851-ba3f-e3cf1e6f7ae6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T13:07:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42480b59-6b29-4f2d-896c-491ce03af675 # Matrix content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69ca5963-4216-495b-9a55-373fdf149fc9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f47de096-e27c-4ea4-b92f-14f81795aeac
        userCondition: null
group: null
groupChildBlockTypes: true
handle: testTypeComplex
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Test type complex'
topLevel: true
