childBlocks: '*'
color: null
conditions: null
description: ''
enabled: true
entryType: 55f73b48-362e-42de-8d71-c7fe0f471b0f # Test Simple type single1
field: aec2d4a4-8e5f-4fab-9a34-f0baecea5d12 # Test neo field 1
fieldLayouts:
  4e610caf-2e5f-4ec3-ae78-431a442148a5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-16T19:12:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06f7732e-7ab3-4fe4-8408-fd96fc9c2f55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a5ecaee-736a-4644-9ad6-9610d3ea30ea
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: testSimpleTypeSingle1
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Test Simple type single1'
topLevel: true
