childBlocks:
  - testMatrixNestedType
  - testSimpleTypeSingle1
  - testnamedblocktype
  - testnamedblocktype2
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: aec2d4a4-8e5f-4fab-9a34-f0baecea5d12 # Test neo field 1
group: null
groupChildBlockTypes: true
handle: testnamedblocktype2
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: testNamedBlockType2
topLevel: true
