childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 56565dd6-81e3-4901-acb2-0e68e57a127c # Test neo container
field: f54c31d7-a088-44f5-844e-abeb61bc67e4 # My field neo
fieldLayouts:
  cfbf4aa5-c5ed-48b7-af39-e0d898c0d4e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-03T17:05:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aec2d4a4-8e5f-4fab-9a34-f0baecea5d12 # Test neo field 1
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3482416d-924d-4218-aba8-f01f9bb6ec7f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa2b542d-b2c8-410c-aa62-58d7bd36d2c1
        userCondition: null
group: null
groupChildBlockTypes: true
handle: testNeoContainer
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Test neo container'
topLevel: true
