childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: d7193139-1ed3-4502-beb9-74584bf39fcf # Test type complex
field: 2adffaf2-3a48-47cd-991f-2d740e397ba2 # test f1neo
fieldLayouts:
  ba846e30-41c4-451f-be0f-a10c1a0e2037:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-06T13:07:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6220f0a0-5b4e-47cf-ae2d-37a08e32e02e # Content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e97e251-0406-46a4-a3d3-0c9d15450dad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T13:07:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42480b59-6b29-4f2d-896c-491ce03af675 # Matrix content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d3ec491-063a-454e-b093-4c6a195717de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 420ed428-be96-4fa5-a994-1544af422a2d
        userCondition: null
group: null
groupChildBlockTypes: true
handle: testTypeComplex
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Test type complex'
topLevel: true
