columnSuffix: null
handle: matrixwithcontentblock
instructions: null
name: 'matrix with content block'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c15a68e6-4524-493d-98aa-8fcacc7b82a5 # test block Container
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 56be00e1-7fb1-4115-b92e-97ed56d35b6a # test page with RichContent1
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
