columnSuffix: null
handle: matrixContent
instructions: null
name: 'Matrix content'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - aa844b03-4bbc-488b-824c-04e4352a82c6 # Test type simple
    -
      __assoc__:
        -
          - uid
          - 11126360-b62a-4e37-b9f0-9359977be230 #  Test Matrix nested type
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
