columnSuffix: null
handle: testMatrixWithNeo
instructions: null
name: 'Test matrix with neo'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 56565dd6-81e3-4901-acb2-0e68e57a127c # Test neo container
    -
      __assoc__:
        -
          - uid
          - d7193139-1ed3-4502-beb9-74584bf39fcf # Test type complex
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
