columnSuffix: null
handle: textMatrixTranslatedPerLanguage
instructions: null
name: 'text Matrix translated per Language'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 9f062eaf-c81c-4da2-8256-77c8046019e6 # test Complex Block Container
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 6f803028-162a-4eea-9092-b7fef7c797d4 # test Entity translated per Language
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 56be00e1-7fb1-4115-b92e-97ed56d35b6a # test page with RichContent1
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: none
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
