columnSuffix: null
handle: text_eachLang
instructions: null
name: 'text eachLang'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
