dateModified: 1776792811
email:
  fromEmail: alexandr.ilyin@gmail.com
  fromName: 'My site'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0e4b9bb1-0ff2-4621-a066-083c6b43b194: 'Test neo container' # Test neo container
    2a020ce3-d3f4-4017-8b71-3e815c155551: 'Test type complex' # Test type complex
    2adffaf2-3a48-47cd-991f-2d740e397ba2: 'test f1neo' # test f1neo
    2b504f54-6a67-4ccd-a87a-e726ee00a817: 'Rich text with image' # Rich text with image
    02c0f60a-04d3-4f05-9ca2-489e2e9df56b: 'NeoContrainer 2' # NeoContrainer 2
    4a1cc9b3-58a6-41e6-abaf-1b6ad618c68d: 'My type' # My type
    6c2105d9-a0b4-4c42-83e9-3f1023fd44ce: testNewBlock # testNewBlock
    6df6ca63-e0ce-4e2c-ba30-cfd5a731c57b: 'Test matrix with neo container' # Test matrix with neo container
    6e86739e-e758-4c83-a361-9457bbd31111: 'Test type complex' # Test type complex
    8bec3f30-4ed9-447c-bb51-37282f26f0a5: NeoContrainer # NeoContrainer
    8e8f003c-0d27-43ab-a9c0-4d9956174727: testNamedBlockType2 # testNamedBlockType2
    8fb5570b-d24b-4f31-b577-b6819aa9f307: 'Test category group' # Test category group
    9cbf8bb6-8e8f-481e-bf49-e1a1206707af: 'Smartcat demo' # Smartcat demo
    047ae459-9c98-4598-957e-629422a7f583: 'My site' # My site
    55a4228c-afd6-4b32-ae1e-668ad9a78b0f: 'My - section' # My - section
    55f73b48-362e-42de-8d71-c7fe0f471b0f: 'Test Simple type single1' # Test Simple type single1
    56bda34c-02ca-4ad3-8745-78c5c62774b3: smartcat # smartcat
    91d13729-866b-4afe-b5c2-ff49f8656e0b: testBlockSubTitlte # testBlockSubTitlte
    91eafe74-3968-40db-9d7b-6d75ec08aaa3: 'Test block container' # Test block container
    289a8b3e-18c1-4bea-8022-7d00c8fc6304: 'Test type simple 2' # Test type simple 2
    836f49b2-7169-4ec1-bf1d-a844ed8ed1ba: 'Test type simple 2' # Test type simple 2
    947df1bf-e646-4be0-bbb3-a93b6f7c334d: 'My neo field 1' # My neo field 1
    5295cfd4-32d6-404b-9127-dcc162d9abcd: 'Rich text' # Rich text
    6220f0a0-5b4e-47cf-ae2d-37a08e32e02e: Content # Content
    8255f5ad-ec03-4ae8-a94f-8e4a960885e5: Simple # Simple
    19664c4f-9a61-42ac-bf1e-c425e4ac4713: myLink # myLink
    42480b59-6b29-4f2d-896c-491ce03af675: 'Matrix content' # Matrix content
    56565dd6-81e3-4901-acb2-0e68e57a127c: 'Test neo container' # Test neo container
    727196d4-774d-484a-bea2-69c54fca7a1f: 'Site -test' # Site -test
    11126360-b62a-4e37-b9f0-9359977be230: ' Test Matrix nested type' #  Test Matrix nested type
    a039e7ff-3f8a-4d3d-a35a-a76e98cff209: ' Test Matrix nested type' #  Test Matrix nested type
    a69eb43f-7566-4d86-8826-598398c334e0: 'Test Simple type single1 2' # Test Simple type single1 2
    a72ff6ea-a555-44ba-b8f5-3e19073674d5: 'Test type complex' # Test type complex
    a1879720-b788-4990-883b-f4de5ac5823c: 'Test Single section 1' # Test Single section 1
    aa844b03-4bbc-488b-824c-04e4352a82c6: 'Test type simple' # Test type simple
    aec2d4a4-8e5f-4fab-9a34-f0baecea5d12: 'Test neo field 1' # Test neo field 1
    b3e0e8f8-5ee9-435b-9de8-6fd908412578: 'seo setting' # seo setting
    c405b783-bbce-439a-b6de-02a6ac32b0f7: MatrixWithNeoContainer # MatrixWithNeoContainer
    c817f919-e93c-44f9-9d5b-256c976a1881: 'Test matrix with neo' # Test matrix with neo
    cbb9d1ca-b408-4fd6-843e-3882ac4532fb: testBlockSubtitle # testBlockSubtitle
    cbfafbed-9efc-4351-8a95-899d008e1075: 'Test structures section1' # Test structures section1
    ce5cd036-fc42-4a6f-8a52-5bb47d597c68: testNamedBlockType # testNamedBlockType
    d2ae12ba-0b8f-4d71-bca2-9bb54be88757: 'Test complex neo container' # Test complex neo container
    d9532f62-1bb3-46e7-b9ae-3a3844990f86: 'Test Simple type single1' # Test Simple type single1
    d7193139-1ed3-4502-beb9-74584bf39fcf: 'Test type complex' # Test type complex
    deedd015-8a49-4a3f-862b-9b2dd7e3a669: 'Test composite objects' # Test composite objects
    dfa82843-6bc5-4c3f-ae51-a49b725e16bb: 'Public Schema' # Public Schema
    e60a6482-d53c-435e-912d-240e7b0ae760: 'Test my site - FR' # Test my site - FR
    e68bc359-7a80-44b3-bb72-385cacbe4a13: 'Tests my site' # Tests my site
    e86bc92f-93f8-4681-b0eb-ff34e96d6efa: 'Test type complex 2' # Test type complex 2
    e96f059b-fe9e-4acd-90c4-bef92d500846: 'Matrix With Neo' # Matrix With Neo
    ea27f769-4640-4c47-a885-2208f0251aa2: 'My site - RU' # My site - RU
    eb9c9d31-8105-42bb-b780-5b6efc68254e: 'Test type simple' # Test type simple
    ed00a43e-81c4-49d6-9ebf-9b2609a64443: 'Tests my site - RU' # Tests my site - RU
    f54c31d7-a088-44f5-844e-abeb61bc67e4: 'My field neo' # My field neo
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: WC7F1TSNSRAUBV8KPHU5W3EM
    schemaVersion: 5.1.0.1
  seomatic:
    edition: standard
    enabled: true
    licenseKey: GISKQAL79ADEH3NHXQ6HU79Q
    schemaVersion: 3.0.13
  smartcat-integration:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'My site'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
