defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4a1cc9b3-58a6-41e6-abaf-1b6ad618c68d # My type
handle: mySection
maxAuthors: 1
name: 'My - section'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e60a6482-d53c-435e-912d-240e7b0ae760: # Test my site - FR
    enabledByDefault: true
    hasUrls: true
    template: my-section/_entry.twig
    uriFormat: 'my-section/{slug}'
  e68bc359-7a80-44b3-bb72-385cacbe4a13: # Tests my site
    enabledByDefault: true
    hasUrls: true
    template: my-section/_entry.twig
    uriFormat: 'my-section/{slug}'
  ed00a43e-81c4-49d6-9ebf-9b2609a64443: # Tests my site - RU
    enabledByDefault: true
    hasUrls: true
    template: my-section/_entry.twig
    uriFormat: 'my-section/{slug}'
structure:
  maxLevels: null
  uid: 76dc7039-8765-40e6-be8d-d74424d9302d
type: structure
